services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      RABBITMQ_HOST: rabbitmq
    volumes:
      - "./:/rails"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  rabbitmq:
    # image: rabbitmq:3
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15692:15692
      - 15672:15672
  
  workers:
    build: .
    command: bundle exec rake jobs:consumers
    depends_on: 
      - rabbitmq
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    volumes:
      - "./:/rails"

  redis: 
     image: redis
     ports:
       - '6379:6379'
  
volumes:
  pgdata: